### ISSUE TITLE
v2 notification doesn't work 

### ISSUE THREAD

**Issue by retoo** [jenkinsci/hipchat-plugin#39] opened 2015-02-23 13:05 UTC
any idea what the problem could be? It happpens in the 'test notification' configuration.

```
Feb 23, 2015 2:03:24 PM jenkins.plugins.hipchat.impl.HipChatV2Service publish
WARNING: HipChat post may have failed. ResponseCode: 400, Response: {
  "error": {
    "code": 400,
    "expected_type": "boolean",
    "field": "notify",
    "message": "Value u'true' for field 'notify' is not of type 'boolean'",
    "type": "Bad Request",
    "validation": "type",
    "value": "true"
  }
}
```

**Comment by aldaris** [comment] 2015-02-23 13:10
This looks a bit odd. I would think this should only happen if the v2 service is accessed using a JSON a payload for the POST ( https://www.hipchat.com/docs/apiv2/method/send_room_notification ).
The error message suggests that the JSON had:

    "notify": "true"

instead of

    "notify: true

But the v2 impl is still using "application/x-www-form-urlencoded" content-type so I'm not really sure why this error could possibly occur.

**Comment by aldaris** [comment] 2015-02-27 13:18
Are there any specific reproduction steps? Can you reliably reproduce this?

**Comment by retoo** [comment] 2015-02-27 16:27
Go to a global configuration, set the api v2 token and press test 
connection. I tried it only once.

**Comment by aldaris** [comment] 2015-02-27 17:21
Hmm, could be that only the Test button doesn't work, IIRC I was able to use v2 tokens from build jobs.

**Comment by aldaris** [comment] 2015-02-28 23:37
I'm unable to reproduce this locally. Are you using a self-hosted HipChat server or api.hipchat.com?
Just to be sure, this is what I did:
* on hipchat.com went to a room that I own, and under Tokens I've created a new one.
* copied that token to the API Token field on the global config page
* selected "Use v2 API"
* pressed "Test configuration" button

**Comment by retoo** [comment] 2015-03-01 05:43
It's a self hosted hip chat sever. I'll try to find out the current version.

**Comment by retoo** [comment] 2015-03-01 10:31
We use 1.1.9 (beta channel)

**Comment by aldaris** [comment] 2015-03-01 18:25
Could you test with the v2testing branch and see if configuration testing works any better? (See also bb03093)

**Comment by retoo** [comment] 2015-03-02 16:00
This worked on my test installation, both test button and notifications of jobs. I don't know yet when I will be able to install it on our production jenkins, but so far it looks good.

**Comment by aldaris** [comment] 2015-03-08 20:20
Committed to master with ba19f04

**Closed by aldaris** 2015-03-08 20:20 UTC
