### ISSUE TITLE
Success messages not populating

### ISSUE THREAD

**Issue by Fyb3roptik** [jenkinsci/hipchat-plugin#83] opened 2016-08-25 20:56 UTC
I have build starting and build failed showing in my chatroom just fine, but success does not work. Not sure why as it is set just like the others, but no matter what I try it does not work.

**Comment by Fyb3roptik** [comment] 2016-08-27 07:35
I should note I am using the AWS Beanstalk plugin as well to zip up my repo and submit it to AWS BS

**Comment by willpracht** [comment] 2016-09-27 21:23
I'm also seeing this behavior, but not only the success notification, but the unstable as well.

Failure seems to work just fine though.

**Comment by aldaris** [comment] 2016-09-27 21:25
Plugin version? Screenshot of config? What kind of job type did you use? Or do you have any reproduction steps at all?

**Comment by willpracht** [comment] 2016-09-27 21:28
Sorry about that! :)

- **Jenkins Version**: 2.7
- **Plugin Version**: 1.0.0
- **Screenshot of configuration attached**
- **Freestyle job**
- **Project Room is the only thing set in the job itself**

<img width="1496" alt="2016-09-27_1625" src="https://cloud.githubusercontent.com/assets/652925/18892512/59fae570-84cf-11e6-8390-3f1b6cf9f2fc.png">

**Comment by willpracht** [comment] 2016-09-27 21:42
Ah! I think I figured out my problem.

"The default notifications listed here will be used when a given project does not specify which events should trigger HipChat notifications."

So am I to believe that the global configuration is only to set the templates (aside from the default notification)?

And then each job will have to set the notifications for themselves?

Wish I could set the global notification for all projects one time for uniformity. :(

**Comment by aldaris** [comment] 2016-09-27 21:44
IIRC the default notifications will be used *only* when the job does not specify any notification on its own. If you have defined a single notification at the job level, the default notification configuration will no longer apply.

**Comment by willpracht** [comment] 2016-09-27 21:46
Ah, okay. And you can only set ONE default notification globally, it seems.

That really throws a wrench into the works :(.

**Comment by aldaris** [comment] 2016-09-27 21:48
Nope, you should be able to have as many default notifications as you want. Assuming that there are no notifications defined at the job level, all default notifications should apply for the job.

**Comment by willpracht** [comment] 2016-09-27 21:48
@aldaris 

OOOOH. Hold on. I wasn't understanding quite right. Let me remove the notifications action from the job. I bet that fixes it. ;p

I was for whatever reason assuming that adding the action, but not creating any notifications would be the same as not having the action. I am so dumb. ;)

**Comment by willpracht** [comment] 2016-09-27 21:50
Well, maybe not. 

New setup was to add the global notifications back in, remove the HipChat notification post-build action completely. 

That resulted in zero notifications for my job, either success or failure.

**Comment by aldaris** [comment] 2016-09-27 21:51
You still need the post build action on the job, otherwise the plugin will never be invoked. Just don't add any notifications to the post build task config at the job level.

**Comment by willpracht** [comment] 2016-09-27 21:52
@aldaris 

Yeah, that's what I had setup before. Unfortunately that was when I was just getting the failure notification.

**Comment by willpracht** [comment] 2016-09-27 22:02
If I add a success notification to the job itself, don't configure anything with it, then it will actually trigger the notification.

This is kind of rough, but seems to be the norm with Jenkins plugins: 
- limited documentation
- wonky features that don't quite make sense
- configuration spread through system configuration and the job itself

**Comment by willpracht** [comment] 2016-09-27 22:16
@aldaris 

Anyway, I appreciate the help with this. Probably just going to live with the individual configuration for now, do some more research. 

Thanks!

**Comment by aldaris** [comment] 2016-10-04 13:20
![global](https://cloud.githubusercontent.com/assets/206692/19075260/0f2874aa-8a3c-11e6-90fa-bebc91f2d404.png)
![job](https://cloud.githubusercontent.com/assets/206692/19075261/114a75b2-8a3c-11e6-9dde-630a12bfa4c4.png)
Have configured my jobs as pics above and I am getting the notifications just fine.

This also means that success notifications are also working for me I'm afraid. Can you provide a minimum set of reproduction steps that always results in this behavior?

**Comment by aldaris** [comment] 2016-10-22 10:21
Sorry guys, but I'm not able to reproduce this, closing until there is a reliable way to reproduce this.

**Closed by aldaris** 2016-10-22 10:21 UTC

**Comment by johnyod** [comment] 2017-09-08 14:49
Hi -- How do i send the jenkins output file (csv) attachment to a particular hipchat room via this plug-in..
